version: 2.1
orbs:
  node: circleci/node@1.1.6
  docker: circleci/docker@1.3.0
  kubernetes: circleci/kuberentes@0.11.1
  aws-ecr: circleci/aws-ecr@6.12.2

jobs:

workflows:
  jobs:
    - aws-ecr/build-and-push-image:
      account-url: AWS_ECR_ACCOUNT_URL
      aws-access-key-id: ACCESS_KEY_ID_ENV_VAR_NAME
      aws-secret-access-key: SECRET_ACCESS_KEY_ENV_VAR_NAME
      dockerfile: Dockerfile
      region: AWS_REGION
      repo: ECR_REPO
      tag: 'latest,<< pipeline.git.revision >>'
